---
- name: Install required packages
  yum: name={{item}} state=installed
  with_items: "{{packages}}"

- name: show installed packages
  command: rpm -qa
  register: packages_out

- debug: var=packages_out
